# Setup
title: Eunsunny's Blog
description: Welcome to Eunsunny blogs / ä½ å¥½ğŸ‘‹ï¼Œ æˆ‘æ˜¯æˆæ©ä»™è¿˜æœ‰è¿™æ˜¯æˆ‘çš„åšå®¢ã€‚è¯·å¤šå¤šå…³ç…§ã€‚/ ì•ˆë…•í•˜ì„¸ìš”! ì„±ì€ì„ ì˜ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤!
url: https://eunsunny.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: EunSeon Seong
  links:
    - https://github.com/eunsunny
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: EunSeon Seong
  url: https://github.com/eunsunny/
  email: click1904@naver.com
